# Generated by Django 5.0.6 on 2024-06-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frondapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginsignupdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('cpassword', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
